---
name: pre-commit Updater

on:
  schedule:
    - cron: "0 9 * * 1-5" # Monday-Friday at 09:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit-updater:
    name: pre-commit Updater
    permissions:
      contents: write
      pull-requests: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/pre-commit-updater.yml@298ae0b81b463fae66f3fd5f7de2422dfa4b7fd0 # v1.1.0
